
#Server Port
server:
  port: 8888

#MariaDB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ManLiHyang
    username: root
    password: taejun1234!

